name: Deploy to AWS
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          cd apps/web && pnpm install
          cd apps/http-backend && pnpm install
      - name: Build Next.js
        run: |
          cd apps/web && pnpm run build
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "3.137.200.237"
          username: "ubuntu"
          key: >-
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAtMyH9xjp4k8dp6yT5i6kqqdqMFLjrUM0OZ5EwOW14yYNLpiD
            bSFMdzEOIKyYoLbPxgVyVe4Qmdp9yVFniC+5jQDvs9eY2paOsfOVYRF3CJnZWw8b
            VYE8gc6h2DQrdfO2pZhqV1P2saQV/RAEoUWG55g0fzaFyu9qyRFimy0p7P0PZT5M
            HXt707V8XKtp7xahu2+hgRUjafJuDFk4asDhB58nE6OvnRWvmg/gBHXAv7lqlz07
            3ZFZqLa1WdVvDWLHCUVDoAqomnmX1GkzP3UHDbRyHe3OWv7Kj7hjS0nY6dvy/hIi
            QdzZjk5SOc4yytncemw6O6F3eSUJXDHyymmfBQIDAQABAoIBAQCpFpAifF5glPV7
            F1/K6tx97czWHO9p32w8ZtSOQ0d0hOXXKjPgIEBPSMWZsVGdHNv8qqNf0iIcgcca
            PNPC/j9eq/2CCKSf6ibSLqkJ+zeEB77L9rjtosxf6kxa04/B5IhxHrZ1rcUOJhOa
            dRyfZ1Lfze1q/CbswDTyjxvVXMvVItJcmWDs1Nn+TIXuKp5LOKwRzQaUM5WUilyz
            sakv8yD49FiCnLsPDz0LJc4w7Q3uQbKPFE8Wx6iTKaSMLihcd0b19Zvnw3QNVbQa
            1Rg+/BAMN394RPSJZYTiLybMRETewEKBzJJAscyWmrS3h13k7fe9gH04LrkA9ent
            zwlmRXcRAoGBAO73vRxKirc7K4jhY2InIrAsktWK47EH0NiYMslPa1He5+BjDVnH
            zm9bEBC3b68NTP+6SuZpO6h39r48FRjSWl+eAYuZx0clacxey0E+cgTyAfzPp8oO
            cvIQ+7fPagbEuTyz0JK2dKaV8A4u/fWc7IqmZy7HJJPBQyhbKxYLFANbAoGBAMGv
            bmKakF+9YkEoUAOuINrPQ1eXykHqgounpc3HMmdt/nVKKy/XrK2dxAKYrP4ejVws
            qPb2xVSWxQuf65a5mxwZXWgCY89AdgSx8Mx62p1uYao3rxmS4/cR6HRexlaNKjEG
            8qMWG4rdEnPhqfll8iUn+JHtGGR60ra0CY4voFUfAoGAMUIFzEAdSdm7hpKXDtNs
            Vg5KEhR4DLTEuvDcfxyMzap594nTZa9HATMvI5L8RYQjXA9Fgysr7fUUenAeFSi/
            EjiarvD639J5dXQQx5kcnaJZAIi5WHAUB4uyp1fszgpc+INEOgm8D96WRgYvuSIo
            rAfS+xR3mLFcq4PnZLrR3EMCgYEAuqzX6mdocS46DezJudJRTjNnh3v/76oT6oBJ
            mNy9otxr3SYAG9t2Tdt5+LqoOUC/JDDTJTxQkqfCAONAkIQRkHKOCVoMUsuhNANA
            wAREwmmJ7iI/PJnL5+y1q7tQ1Ei4eopkv3TmVN+gElpUldCBIvi0ZgkrcmTCxF8f
            upACqycCgYBh/TK/D1KhCaJpZTfD1HK3CA8wa8EG23AdVf4N97qZ1Og/Ef1oasy1
            Q80V/0K29yNN0icwHqrn6FqUQcbcQDMQj/4ZEBblkn3GIf4N0SvuEiX8Wf1+oOhm
            dbHoCXTb6vpFgsu356mLOX0u5te4dMCch2lTCEPKqnzbPJBug2DHSg== -----END
            RSA PRIVATE KEY-----
          script: |
            cd /home/ubuntu/Luumi
            git pull origin main
            pnpm install
            cd apps/web && pnpm run build
            pm2 restart web
            pm2 restart backend
